---
version: 3

images:
  base_image:
    name: quay.io/fedora/fedora:39

dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  system:
  - openssh-clients
  - sshpass
  galaxy:
    collections:
    - name: cisco.ios
    - name: community.network
    - name: cisco.asa
    - name: cisco.nxos
  python:
  - Jinja2
