---
# Playbook gathers show command output once devices are live and reachable
# Playbook starts by asking the username/password of user
# - this ##does not## back up device configurations prior to running , but no need as only show commands are run
# - List of devices are obtained from ansible inventory file(s)
# - Specific tags can be used for device category (switch, router, nxos)
#
## Begin by obtaining login variables and setting connection type
- name: Pull Cisco IOS Information, put in file
  hosts: all
  connection: network_cli
  gather_facts: false
  vars_prompt:
   - name: "ansible_user"
     prompt: "What is your username? "
     private: false

   - name: "ansible_password"
     prompt: "What is your password? "
     private: true

  tasks:

   # Set a timestamp variable
   - name: Create timestamp
     ansible.builtin.set_fact:
      timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d-at-%H--%M--%S') }}"
      # removed the colon ":" in timestamp as windows has issues with this when accessing saved files and replaced with double dashes "--"
     tags:
      - switch
      - router
      - nxos
      - l3cs

   # Create folder to store output if not present
   - name: Create directory - for output
     ansible.builtin.file:
      path: ./output
      state: directory
      # Set permissions using octal so leading 0 , set to User=RW , Group=R , Other=R
      mode: "0644"
     tags:
      - switch
      - router
      - nxos
      - l3cs

# #########################Block for IOS Access Switches##########################
   - name: For IOS Switches - Access
     when: "'access' in group_names"
     tags:
      - switch
     block:
      - name: Run multiple IOS commands on remote nodes
        cisco.ios.ios_command:
         commands:
          - show version
          - show int status
          - show inventory
          - show module
          - show environment power all
          - show cdp neighbors
          - show spanning-tree root
          - show etherchannel summary
          - show environment all
          - show power inline
          - show switch detail
          - show stack-power detail
        register: switch_output

      - name: Show output to files
        ansible.builtin.template:
         # Set permissions using octal so leading 0 , set to User=RW , Group=R , Other=R
         mode: "0644"
         src: ./templates/output_switch_template.j2
         dest: ./output/{{ inventory_hostname }}.{{ timestamp }}.switch_report.txt

# ##########################Block for IOS Aggregation/Distribution Switches##########################
   - name: For IOS Switches - Agg/Dist
     when: "'distriubution' in group_names"
     tags:
      - switch
     block:
      - name: Run multiple IOS commands on remote nodes
        cisco.ios.ios_command:
         commands:
          - show version
          - show int status
          - show inventory
          - show module
          - show environment power all
          - show cdp neighbors
          - show spanning-tree root
          - show etherchannel summary
          - show environment all
          - show power inline
        register: agg_switch_output

      - name: Show output to files
        ansible.builtin.template:
         # Set permissions using octal so leading 0 , set to User=RW , Group=R , Other=R
         mode: "0644"
         src: ./templates/output_agg_switch_template.j2
         dest: ./output/{{ inventory_hostname }}.{{ timestamp }}.switch_report.txt

# ##########################Block for IOS Routers##########################
   - name: For IOS Routers
     when: "'routers' in group_names"
     tags:
      - router
     block:
      - name: Run multiple IOS commands on remote nodes
        cisco.ios.ios_command:
         commands:
          - show version
          - show environment
          - show ip int brief
          - show ip eigrp neighbors
          - show ip eigrp interfaces
          - show ip ospf interface brief
          - show ip ospf interface
          # If not running address families may be deriable to run different bgp command
          # To prevent requiring update of jinja template only uncomment one of the two bgp commands
          # - show ip bgp summary
          - show bgp all summary
          - show ip route
          - show cdp neighbors
          - show ip protocols
          - show inventory
        register: router_output

      - name: Show output to files
        ansible.builtin.template:
         # Set permissions using octal so leading 0 , set to User=RW , Group=R , Other=R
         mode: "0644"
         src: ./templates/output_router_template.j2
         dest: ./output/{{ inventory_hostname }}.{{ timestamp }}.router_report.txt

# ##########################Block for NXOS##########################
   - name: For NXOS
     when: "'nexus' in group_names"
     tags:
      - nxos
     block:
      - name: Run multiple NXOS commands on remote nodes
        cisco.nxos.nxos_command:
         commands:
          - show version
          - show interface brief
          - show inventory
          - show module
          - show cdp neighbors
          - show spanning-tree root
          - show vpc
          - show fex
          - show environment
          - show environment fex all
        register: nxos_output

      - name: Show output to files
        ansible.builtin.template:
         # Set permissions using octal so leading 0 , set to User=RW , Group=R , Other=R
         mode: "0644"
         src: ./templates/output_nexus_template.j2
         dest: ./output/{{ inventory_hostname }}.{{ timestamp }}.switch_report.txt

# ##########################Block for L3 Core Device L3 Router info##########################
   - name: For L3 Core Switch Router Info
     when: "'l3cs' in group_names"
     tags:
      - l3cs
     block:
      - name: Run multiple IOS commands on remote nodes
        cisco.ios.ios_command:
         commands:
          - show version
          - show ip int brief
          - show ip eigrp neighbors
          - show ip eigrp interfaces
          - show ip ospf interface brief
          - show ip ospf interface
          - show ip bgp summary
          - show ip route
          - show cdp neighbors
          - show ip protocols
        register: l3cs_output

      - name: Show output to files
        ansible.builtin.template:
         # Set permissions using octal so leading 0 , set to User=RW , Group=R , Other=R
         mode: "0644"
         src: ./templates/output_l3cs_template.j2
         dest: ./output/{{ inventory_hostname }}.{{ timestamp }}.l3_core_switch_report.txt

# ##########################Block for L3 Core Device L2 Switch info##########################
   - name: For L3 Core Switch Switch Info
     when: "'l3cs' in group_names"
     tags:
      - l3cs
     block:
      - name: Run multiple IOS commands on remote nodes
        cisco.ios.ios_command:
         commands:
          - show version
          - show int status
          - show inventory
          - show module
          - show environment
          - show cdp neighbors
          - show spanning-tree root
          - show etherchannel summary
          - show environment all
          - show power inline
        register: l2cs_switch_output

      - name: Show output to files
        ansible.builtin.template:
         # Set permissions using octal so leading 0 , set to User=RW , Group=R , Other=R
         mode: "0644"
         src: ./templates/output_l2cs_switch_template.j2
         dest: ./output/{{ inventory_hostname }}.{{ timestamp }}.l2_core_switch_report.txt

# ##########################Block for WLC info##########################
   - name: For WLC Info
     when: "'wlc' in group_names"
     tags:
      - wlc
     block:
      - name: Run multiple AireOS commands on remote nodes
        community.network.aireos_command:
         commands:
          - show version
        register: wlc_output

      - name: Show output to files
        ansible.builtin.template:
         # Set permissions using octal so leading 0 , set to User=RW , Group=R , Other=R
         mode: "0644"
         src: ./templates/output_wlc_template.j2
         dest: ./output/{{ inventory_hostname }}.{{ timestamp }}.wlc_report.txt

# ##########################Block for FW (ASA) info##########################
   - name: For FW (ASA) Info
     when: "'fw' in group_names"
     tags:
      - fw
     block:
      - name: Run multiple ASA commands on remote nodes
        cisco.asa.asa_command:
         commands:
          - show version
        register: fw_asa_output

      - name: Show output to files
        ansible.builtin.template:
         # Set permissions using octal so leading 0 , set to User=RW , Group=R , Other=R
         mode: "0644"
         src: ./templates/output_fw_template.j2
         dest: ./output/{{ inventory_hostname }}.{{ timestamp }}.fw_report.txt
